### ISSUE TITLE
Maybe a mastodon bot?

### ISSUE THREAD

**Issue by tori3ama** [chiubaca/shiba-every-hour#2]
Hi,

As a shiba fan experiencing different twitter issues recently, I'd like to see a mastodon bot for cute shiba, I could try to create a PR for this if you also want to see this :)

**Comment by chiubaca** [comment]
your wish is my command ... ✨ 😄  🐕 

https://mas.to/@ShibaEveryHour

**Comment by tori3ama** [comment]
Wow, thanks!

**Comment by tori3ama** [comment]
Sorry to disturb, but the mastodon bot stop working for days, but twitter bot is still working, could you please help check? Thanks!

**Comment by chiubaca** [comment]
@radaiming thanks for bringing this to my attention. I will get it back up and running ASAP!

**Comment by tori3ama** [comment]
Hi, the mastodon bot stopped working for a month, could you please help check? Thanks. 😭

**Comment by chiubaca** [comment]
Thanks for letting me know! It's should be back now 👌

**Comment by tori3ama** [comment]
Thank you again!

**Comment by tori3ama** [comment]
Hi, the bot stopped again, could you please help check? Thanks😭

**Comment by chiubaca** [comment]
yeah i'm aware... related to https://github.com/azrogers/ShibeOnline/issues/3

Hope the API comes back .... 😢

**Comment by tori3ama** [comment]
Just find it back! Really thank you! The world is incomplete without shiba inu ♥️💙💜🖤💛💚🧡🤎🤍🩷🩶🩵

**Comment by chiubaca** [comment]
thank you for the support, enjoy!
