### ISSUE TITLE
GitHub Actions workflow is disabled, no more shiba posted 😭

### ISSUE THREAD

**Issue by tori3ama** [chiubaca/shiba-every-hour#3]
Could you re-enable it? https://github.com/chiubaca/shiba-every-hour/actions/workflows/post-shibe.yml

Maybe something like this could help: https://github.com/marketplace/actions/keepalive-workflow

**Comment by chiubaca** [comment]
Thanks for letting me know! I re-enable it this morning so shibe bot should be back .

Will look into the keep alive workflow👍

**Comment by tori3ama** [comment]
Thanks!!💕
